### ISSUE TITLE
underlyingPriceAtClose wasn't so there must be a little bug

### ISSUE THREAD

**Issue by ffahimi** [Chocksy/qc-options-framework#35]
I didn't investigate but the underlyingPriceAtOpen was returning underlyingprice and underlyingPriceAtClose wasn't so there must be a little bug, I noticed this when I was trying to get the price in the assignment function handleassignment through the assignedPosition

**Comment by Chocksy** [comment]
I think this was never implemented. Good find. We need to add a similar method at EndOfDay to store the underlying price :)

**Comment by ffahimi** [comment]
I am using contractUtils.getUnderlyingLastPrice and this can be implemented also in the positions if needed. I close this issue because I have another way of accessing this.
